# Generated by Django 5.2.6 on 2025-09-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='api_key',
            field=models.CharField(blank=True, default='Insira uma chave de API', help_text='Chave da api GEMINI que será utilizada pelo usuário', max_length=500, verbose_name='Chave da API'),
        ),
        migrations.AlterField(
            model_name='user',
            name='system_prompt',
            field=models.CharField(blank=True, default='Teste', help_text='Prompt de sistema que determina o comportamento da IA', max_length=10000, verbose_name='Prompt de sistema'),
        ),
    ]
