# Generated by Django 5.2.6 on 2025-09-19 19:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PsyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_number', models.PositiveIntegerField(editable=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('content', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psy_records', to='patients.patient')),
            ],
            options={
                'ordering': ['patient', 'record_number'],
                'unique_together': {('patient', 'record_number')},
            },
        ),
    ]
