# Generated by Django 5.2.6 on 2025-09-30 05:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psy_records', '0002_alter_psyrecord_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psyrecord',
            name='content',
            field=models.TextField(blank=True, verbose_name='Conteúdo'),
        ),
        migrations.AlterField(
            model_name='psyrecord',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='psyrecord',
            name='record_number',
            field=models.PositiveIntegerField(editable=False, verbose_name='Número do registro'),
        ),
    ]
