# Generated by Django 5.2.6 on 2025-09-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='clinical_analysis',
            field=models.TextField(blank=True, null=True, verbose_name='Análise'),
        ),
        migrations.AddField(
            model_name='patient',
            name='clinical_conclusion',
            field=models.TextField(blank=True, null=True, verbose_name='Conclusões'),
        ),
        migrations.AddField(
            model_name='patient',
            name='clinical_demand',
            field=models.TextField(blank=True, null=True, verbose_name='Demanda'),
        ),
        migrations.AddField(
            model_name='patient',
            name='clinical_procedures',
            field=models.TextField(blank=True, null=True, verbose_name='Procedimentos'),
        ),
        migrations.AddField(
            model_name='patient',
            name='objectives',
            field=models.TextField(blank=True, null=True, verbose_name='Objetivos'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Priemiro nome'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nome completo'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='second_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Segundo nome'),
        ),
    ]
